# Generated by Django 5.1.1 on 2024-09-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите заголовок события', max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, help_text='Загрузите превью события', null=True, upload_to='diary/image', verbose_name='Превью события')),
                ('context', models.TextField(help_text='Введите описание события', verbose_name='Описание события')),
                ('date_event', models.TextField(blank=True, help_text='Введите дату события', null=True, verbose_name='Дата события')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи')),
                ('is_active', models.BooleanField(default=True, help_text='Разрешить эту запись видеть всем?')),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
            },
        ),
    ]
