# Generated by Django 5.1.1 on 2024-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date_event',
            field=models.CharField(blank=True, help_text='Введите дату события', max_length=20, null=True, verbose_name='Дата события'),
        ),
    ]
