# Generated by Django 5.1.1 on 2024-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='context',
            field=models.TextField(verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date_event',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary/image', verbose_name='Превью события'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
